backend:
  name: github
  repo: brayckner/braycknermedia

media_folder: "static/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "netlify/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}